### ISSUE TITLE
[BUG] Compilation error on `get_cache_idx` in debug

### ISSUE THREAD

**Issue by lowener** [rapidsai/raft#1553]
**Describe the bug**
Compiling Raft in debug is failing due to this error:
```
raft/cpp/include/raft/util/cache_util.cuh:331:27: error: inline function 'void raft::cache::get_cache_idx(int*, int, int*, int, int, int*, int*, bool*, int)' given attribute 'noinline' [-Werror]
  331 | __global__ inline void get_cache_idx(int* keys,
      |                           ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
It seems to have been introduced in PR #1492

**Environment**
CUDA 11.8

**Comment by lowener** [comment]
Duplicate of #1511 so I'll close this one
